# Generated by Django 5.0.14 on 2025-04-19 16:45

import datetime
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('campaign_code', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Código Campaña')),
                ('campaign_name', models.CharField(max_length=255, verbose_name='Nombre Campaña')),
                ('start_date', models.DateTimeField(help_text='Fecha y hora de inicio de la campaña', verbose_name='Fecha Inicio')),
                ('end_date', models.DateTimeField(blank=True, help_text='Fecha y hora de fin (opcional)', null=True, verbose_name='Fecha Fin')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('target_audience', models.JSONField(blank=True, default=dict, help_text='Descripción del público objetivo (JSON)', verbose_name='Público Objetivo')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto')),
                ('is_active', models.BooleanField(default=True, help_text='¿La campaña está activa actualmente?', verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Campaña',
                'verbose_name_plural': 'Campañas',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Formulario')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
            ],
            options={
                'verbose_name': 'Formulario',
                'verbose_name_plural': 'Formularios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Puesto')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('permissions', models.JSONField(blank=True, default=dict, help_text='Permisos específicos para este puesto (estructura JSON)', verbose_name='Permisos JSON')),
            ],
            options={
                'verbose_name': 'Puesto de Trabajo',
                'verbose_name_plural': 'Puestos de Trabajo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Transferencia, Tarjeta, PayPal', max_length=50, unique=True, verbose_name='Nombre Método Pago')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Método de Pago',
                'verbose_name_plural': 'Métodos de Pago',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Nombre Proveedor')),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='Persona de Contacto')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('rating', models.DecimalField(decimal_places=1, default=Decimal('5.0'), help_text='Calificación interna (1-5)', max_digits=3, verbose_name='Calificación')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('notes', models.TextField(blank=True, help_text='Notas internas sobre el proveedor', verbose_name='Notas Internas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('code', models.CharField(help_text='Código corto de la categoría (ej. MKT, DEV)', max_length=10, primary_key=True, serialize=False, verbose_name='Código Categoría')),
                ('name', models.CharField(help_text='Nombre descriptivo de la categoría', max_length=100, verbose_name='Nombre Categoría')),
            ],
            options={
                'verbose_name': 'Categoría de Servicio',
                'verbose_name_plural': 'Categorías de Servicios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TransactionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ej: Pago Cliente, Reembolso, Gasto Proveedor', max_length=50, unique=True, verbose_name='Nombre Tipo Transacción')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='Requiere Aprobación')),
            ],
            options={
                'verbose_name': 'Tipo de Transacción',
                'verbose_name_plural': 'Tipos de Transacciones',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Short internal alias (e.g., 'dev', 'mktg'). Use constants from roles.py.", max_length=50, unique=True, verbose_name='Internal Name')),
                ('display_name', models.CharField(help_text='User-friendly name shown in interfaces.', max_length=100, verbose_name='Display Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'User Role',
                'verbose_name_plural': 'User Roles',
                'ordering': ['display_name'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(help_text='Descripción de la acción realizada', max_length=255, verbose_name='Acción')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('details', models.JSONField(blank=True, default=dict, help_text='Detalles adicionales en formato JSON', verbose_name='Detalles')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Teléfono')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('country', django_countries.fields.CountryField(blank=True, help_text='País del cliente', max_length=2, null=True, verbose_name='País')),
                ('company_name', models.CharField(blank=True, help_text='Nombre de la empresa (si aplica)', max_length=150, null=True, verbose_name='Nombre de Empresa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('preferred_contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Teléfono'), ('whatsapp', 'WhatsApp'), ('other', 'Otro')], max_length=20, null=True, verbose_name='Método Contacto Preferido')),
                ('brand_guidelines', models.FileField(blank=True, null=True, upload_to='customers/brand_guidelines/', verbose_name='Guías de Marca')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField(default=datetime.date.today, verbose_name='Fecha Contratación')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('salary', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Salario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='api.jobposition', verbose_name='Puesto')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
        migrations.CreateModel(
            name='FormQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='Texto de la Pregunta')),
                ('order', models.PositiveIntegerField(default=0, help_text='Orden de aparición en el formulario', verbose_name='Orden')),
                ('required', models.BooleanField(default=True, verbose_name='Requerida')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.form', verbose_name='Formulario')),
            ],
            options={
                'verbose_name': 'Pregunta de Formulario',
                'verbose_name_plural': 'Preguntas de Formularios',
                'ordering': ['form', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='Mensaje')),
                ('read', models.BooleanField(db_index=True, default=False, verbose_name='Leída')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('link', models.URLField(blank=True, help_text='Enlace relevante (ej. a un pedido, tarea)', null=True, verbose_name='Enlace')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Recepción')),
                ('date_required', models.DateTimeField(help_text='Fecha límite solicitada por el cliente', verbose_name='Fecha Requerida')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('CONFIRMED', 'Confirmado'), ('PLANNING', 'Planificación'), ('IN_PROGRESS', 'En Progreso'), ('QUALITY_CHECK', 'Control de Calidad'), ('PENDING_DELIVERY', 'Pendiente Entrega'), ('DELIVERED', 'Entregado'), ('CANCELLED', 'Cancelado'), ('ON_HOLD', 'En Espera')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('payment_due_date', models.DateTimeField(blank=True, help_text='Fecha límite para el pago (si aplica)', null=True, verbose_name='Vencimiento Pago')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Nota Interna')),
                ('priority', models.PositiveIntegerField(default=3, help_text='Prioridad (ej. 1=Alta, 5=Baja)', verbose_name='Prioridad')),
                ('completed_at', models.DateTimeField(blank=True, editable=False, help_text="Fecha y hora de finalización (status='DELIVERED')", null=True, verbose_name='Fecha Completado')),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, help_text='Calculado de OrderService. Actualizado automáticamente.', max_digits=12, verbose_name='Monto Total')),
                ('customer', models.ForeignKey(help_text='Cliente que realiza el pedido', on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='api.customer', verbose_name='Cliente')),
                ('employee', models.ForeignKey(blank=True, help_text='Empleado responsable principal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to='api.employee', verbose_name='Empleado Asignado')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['priority', '-date_received'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(blank=True, help_text='Número de factura (puede autogenerarse)', max_length=50, unique=True, verbose_name='Número Factura')),
                ('date', models.DateField(default=datetime.date.today, help_text='Fecha de emisión de la factura', verbose_name='Fecha Emisión')),
                ('due_date', models.DateField(help_text='Fecha de vencimiento del pago', verbose_name='Fecha Vencimiento')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), editable=False, max_digits=12, verbose_name='Monto Pagado')),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('SENT', 'Enviada'), ('PAID', 'Pagada'), ('PARTIALLY_PAID', 'Parcialmente Pagada'), ('OVERDUE', 'Vencida'), ('CANCELLED', 'Cancelada'), ('VOID', 'Anulada Post-Pago')], db_index=True, default='DRAFT', max_length=20, verbose_name='Estado')),
                ('notes', models.TextField(blank=True, help_text='Notas o términos de la factura', verbose_name='Notas/Términos')),
                ('order', models.ForeignKey(help_text='Pedido al que corresponde la factura', on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='api.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Deliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, help_text='Archivo entregable (opcional inicialmente)', null=True, upload_to='deliverables/%Y/%m/', verbose_name='Archivo')),
                ('description', models.TextField(help_text='Descripción clara de la tarea o entregable', verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Versión')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('ASSIGNED', 'Asignado'), ('IN_PROGRESS', 'En Progreso'), ('PENDING_APPROVAL', 'Pendiente Aprobación Cliente'), ('PENDING_INTERNAL_APPROVAL', 'Pendiente Aprobación Interna'), ('REQUIRES_INFO', 'Requiere Info Adicional'), ('REVISION_REQUESTED', 'Revisión Solicitada'), ('APPROVED', 'Aprobado'), ('COMPLETED', 'Completado'), ('REJECTED', 'Rechazado')], db_index=True, default='PENDING', max_length=30, verbose_name='Estado')),
                ('due_date', models.DateField(blank=True, help_text='Fecha límite para este entregable', null=True, verbose_name='Fecha Límite')),
                ('feedback_notes', models.TextField(blank=True, help_text='Comentarios o feedback recibido', verbose_name='Notas de Feedback')),
                ('assigned_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliverables', to='api.employee', verbose_name='Empleado Asignado')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='api.order', verbose_name='Pedido')),
                ('assigned_provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_deliverables', to='api.provider', verbose_name='Proveedor Asignado')),
            ],
            options={
                'verbose_name': 'Entregable/Tarea',
                'verbose_name_plural': 'Entregables/Tareas',
                'ordering': ['order', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('code', models.CharField(help_text='Código único del servicio (ej. OD001)', max_length=10, primary_key=True, serialize=False, verbose_name='Código Servicio')),
                ('name', models.CharField(help_text='Nombre descriptivo del servicio', max_length=255, verbose_name='Nombre Servicio')),
                ('is_active', models.BooleanField(default=True, help_text='¿El servicio está activo y disponible para la venta?', verbose_name='Activo')),
                ('ventulab', models.BooleanField(default=False, help_text='¿Es un servicio interno o especial de Ventulab?', verbose_name='Ventulab')),
                ('is_package', models.BooleanField(default=False, help_text='¿Este servicio es un paquete que agrupa otros?', verbose_name='Es Paquete')),
                ('is_subscription', models.BooleanField(default=False, help_text='¿Este servicio es una suscripción recurrente?', verbose_name='Es Suscripción')),
                ('audience', models.TextField(blank=True, help_text='Público objetivo principal de este servicio', null=True, verbose_name='Público Objetivo')),
                ('detailed_description', models.TextField(blank=True, help_text='Descripción más detallada del servicio', null=True, verbose_name='Descripción Detallada')),
                ('problem_solved', models.TextField(blank=True, help_text='Qué problema o necesidad soluciona este servicio', null=True, verbose_name='Problema que Soluciona')),
                ('campaign', models.ForeignKey(blank=True, help_text='Campaña promocional asociada directa (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promoted_services', to='api.campaign', verbose_name='Campaña Asociada')),
                ('category', models.ForeignKey(help_text='Categoría principal del servicio', on_delete=django.db.models.deletion.PROTECT, related_name='services', to='api.servicecategory', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='provider',
            name='services_provided',
            field=models.ManyToManyField(blank=True, help_text='Servicios que ofrece este proveedor', related_name='providers', to='api.service', verbose_name='Servicios Ofrecidos'),
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio unitario en el momento de añadir a la orden', max_digits=12, verbose_name='Precio Unitario')),
                ('note', models.TextField(blank=True, help_text='Notas específicas para este servicio en esta orden', verbose_name='Nota')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.order', verbose_name='Pedido')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_lines', to='api.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Servicio del Pedido',
                'verbose_name_plural': 'Servicios del Pedido',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServiceFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_type', models.CharField(choices=[('differentiator', 'Diferenciador'), ('benefit', 'Beneficio'), ('caracteristicas', 'Características'), ('process', 'Proceso'), ('result', 'Resultado Esperado')], help_text='Tipo de característica', max_length=20, verbose_name='Tipo')),
                ('description', models.TextField(help_text='Descripción de la característica, beneficio, etc.', verbose_name='Descripción')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='api.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Característica de Servicio',
                'verbose_name_plural': 'Características de Servicios',
                'ordering': ['service', 'feature_type'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se registró el pago', verbose_name='Fecha Pago')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Moneda')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('COMPLETED', 'Completado'), ('FAILED', 'Fallido'), ('REFUNDED', 'Reembolsado')], db_index=True, default='COMPLETED', max_length=20, verbose_name='Estado')),
                ('transaction_id', models.CharField(blank=True, help_text='ID de la transacción externa si aplica', max_length=100, null=True, verbose_name='ID Transacción Externa')),
                ('notes', models.TextField(blank=True, help_text='Notas sobre el pago', verbose_name='Notas')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.invoice', verbose_name='Factura')),
                ('method', models.ForeignKey(help_text='Método utilizado para el pago', on_delete=django.db.models.deletion.PROTECT, to='api.paymentmethod', verbose_name='Método de Pago')),
                ('transaction_type', models.ForeignKey(help_text='Tipo de transacción (ej. pago, reembolso)', on_delete=django.db.models.deletion.PROTECT, to='api.transactiontype', verbose_name='Tipo Transacción')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('primary_role', models.ForeignKey(help_text="The main mandatory role defining the user's core function.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_users', to='api.userrole', verbose_name='Primary Role')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Respuesta proporcionada por el cliente', verbose_name='Respuesta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Respuesta')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='api.customer', verbose_name='Cliente')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.form', verbose_name='Formulario')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='api.formquestion', verbose_name='Pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de Formulario',
                'verbose_name_plural': 'Respuestas de Formularios',
                'ordering': ['created_at'],
                'unique_together': {('customer', 'form', 'question')},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('currency', models.CharField(default='EUR', help_text='Código ISO 4217 (ej. EUR, USD, CLP, COP)', max_length=3, verbose_name='Moneda')),
                ('effective_date', models.DateField(default=datetime.date.today, help_text='Fecha desde la que este precio es válido', verbose_name='Fecha Efectiva')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='api.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Precio Histórico',
                'verbose_name_plural': 'Historial de Precios',
                'ordering': ['service', 'currency', '-effective_date'],
                'get_latest_by': 'effective_date',
                'unique_together': {('service', 'currency', 'effective_date')},
            },
        ),
        migrations.CreateModel(
            name='CampaignService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Descuento aplicado a este servicio en la campaña (%)', max_digits=5, verbose_name='Descuento (%)')),
                ('additional_details', models.TextField(blank=True, null=True, verbose_name='Detalles Adicionales')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='included_services', to='api.campaign', verbose_name='Campaña')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='api.service', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Servicio de Campaña',
                'verbose_name_plural': 'Servicios de Campañas',
                'unique_together': {('campaign', 'service')},
            },
        ),
        migrations.CreateModel(
            name='UserRoleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Assignment Active')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Assigned At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_assignments', to='api.userrole', verbose_name='Secondary Role/Access')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_role_assignments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Secondary Role / Access Assignment',
                'verbose_name_plural': 'Secondary Role / Access Assignments',
                'ordering': ['user__username', 'role__display_name'],
                'unique_together': {('user', 'role')},
            },
        ),
    ]
